### ISSUE TITLE
A couple of errors in your code?

### ISSUE THREAD

**Issue by billdavisjr** [Code-Institute-Solutions/FromJavaScriptTojQuery#4]
In the code:

for (var i = 0; i < ul[0].children.length; i++) {
    li = ul[0].children;		
    li.style.backgroundColor = 'pink';
}

shouldn't:  li = ul[0].children;		
be li=ui[0].chilldren[i] 

And shouldn't the code:

ul.removeClass('active').css('pink'); 

be something like addClass? You are ADDING to the css in the for loop that code is intended to replace?.  And where's the indication what CSS is being added (background color) ?  What .css() are you turning pink?

**Comment by NielMc** [comment]
I have edited the for loop code to match what you see in the video. 
The second piece is pseudo-code so is not intended to work and is just in the video to show that manipulating the DOM with native js is limiting.
